name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify your Node.js version
    - name: Install dependencies
      run: npm install
    - name: Clean
      run: npm run clean
    - name: Build
      run: npm run build
    - name: Package
      run: npm run package
    - name: Run unit tests
      run: npm test
